professeur/authentication/urls.py
from django.urls import include, path
from . import views

app_name='authentication'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
]

professeur/curriculum/urls.py
from django.urls import include, path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.index, name='index'),
    path('skills/', views.skills, name='skills'),
    path('works/', views.works, name='works'),
]

professeur/professeur/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

professeur/teaching/urls.py
from django.urls import include, path
from . import views

app_name='teaching'
urlpatterns = [
    path('courses', views.courses, name='courses'),
    path('details/', views.details, name='details'),
    path('list/', views.list, name='list'),
    path('training/', views.training, name='training'),
]

professeur/website/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authentication/', include('authentication.urls')),
    path('curriculum/', include('curriculum.urls')),
    path('teaching/', include('teaching.urls')),
    path('checkup', views.checkup, name='checkup')
    
]

professeur/teaching/models.py
from django.db import models
from multiselectfield import MultiSelectField

STATUT = [
    ('C', 'En cours'),
    ('A', 'En attente'),
    ('T', 'Terminé'),
]


class Module(models.Model):
    nom = models.CharField(max_length=100)
    date_add = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Module'
        verbose_name_plural = 'Modules'

    def __str__(self):
        return self.nom


class Discipline(models.Model):
    titre = models.CharField(max_length=255)
    image = models.ImageField()
    description = models.CharField(max_length=255)
    lien = models.URLField()
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    date_add = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Discipline'
        verbose_name_plural = 'Disciplines'

    def __str__(self):
        return self.titre


# Setting MATIERES with all the recorded disciplines
mats = Discipline.objects.all()
MATIERES = []
for mat in mats:
    MATIERES.append((mat.id, mat.titre))


class Training(models.Model):
    intitule = models.CharField(max_length=100, verbose_name='Intitulé')
    date_debut = models.DateField(verbose_name='Date de début')
    date_fin = models.DateField(verbose_name='Date de fin')
    mot_de_passe = models.CharField(max_length=255)
    matieres = MultiSelectField(choices=MATIERES, verbose_name='Matières')
    statut = models.CharField(max_length=1, choices=STATUT, verbose_name='Etat')
    date_add = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Formation'
        verbose_name_plural = 'Formations'

    def __str__(self):
        return self.intitule

professeur/teaching/views.py
from django.shortcuts import render
from teaching.models import Discipline, Training

context = {}

def courses(request):
    return render(request, 'teaching/courses.html')

def details(request):
    return render(request, 'teaching/details.html')

def list(request):
    trainings = Training.objects.all()
    context['trainings'] = trainings
    return render(request, 'teaching/list.html', context)

def training(request, id_training=1):

    disciplines = []

    # Select the incoming training
    training = Training.objects.get(id=id_training)

    # Select the disciplines of the incoming training
    for id_mat in training.matieres:
        discipline = Discipline.objects.get(id=id_mat)
        disciplines.append(discipline)

    context['training'] = training
    context['disciplines'] = disciplines

    return render(request, 'teaching/training.html', context)

professeur/teaching/templates/teaching/list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block 'banner' %}{% endblock %}
{% block 'main' %}


    <div class='container' style="margin-top: 100px;">
        <div style="color: #3F3F3F; text-transform: uppercase; font-size: 2rem; margin: 20px 0;">Choisissez une formation</div>
        <hr>

        <div class="accordeon" style="/*border: 1px solid green;*/">
            <div hidden aria-hidden="true">
                <svg xmlns="http://www.w3.org/2000/svg">
                    <symbol viewBox="0 0 24 24" id="icon-tabClosed">
                        <path d="M7 11.5h10v1H7z" />
                    </symbol>
                    <symbol viewBox="0 0 24 24" id="icon-tabOpened">
                        <path d="M11.5 7h1v10h-1z" />
                    </symbol>
                </svg>
            </div>
            <main role="main" style="/*border: 1px solid blue;*/">
                <section class="block cv_section" style="/*border: 1px solid black; */width: 100%;">
                    <div data-role="accordion" data-multiselectable="true">
                        {% for training in trainings %}
                        <h3 class="tab">
                            <button id="tab{{ training.id }}" aria-controls="panel{{ training.id }}">{{ training.intitule }}
                                <svg aria-hidden="true" class="icon-tab">
                                    <use xlink:href="#icon-tabClosed" class="dash"></use>
                                    <use xlink:href="#icon-tabOpened" class="pipe"></use>
                                </svg>
                            </button>
                        </h3>
                        <div id="panel{{ training.id }}" class="panel" aria-labelledby="tab{{ training.id }}">
                            <p>{{ training.intitule }} - {{ training.intitule }}</p>
                            <form class="text-center" method="get" action="{% url 'teaching:training' %}">
                                <div class="form-group col-md-6">
                                    <input type="password" class="form-control mb-2" name="pwd" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrer le mot de passe de cette formation">
                                </div>
                                <div class="col-md-6">
                                    <button type="submit" class="btn btn-primary mb-2" style="width: 100%;">Accéder à la formation</button>
                                </div>
                            </form>
                        </div>
                        {% endfor %}
                    </div>
                </section>
            </main>
        </div>
    </div>

    <script src="{% static 'js/accordion.js' %}"></script>
    <script>
        var accordeons = Array.from( document.querySelectorAll( '[data-role="accordion"]' ));
        window.accordeons = accordeons.map( function( accordeon ){
            var accordion = new window.Accordion( accordeon );
            accordion.on( 'show', open );
            accordion.on( 'hide', close );
            accordion.mount();
            return accordion;
        });
    </script>

{% endblock %}

professeur/teaching/templates/teaching/training.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
	<meta name="keywords" content="">
	<meta name="description" content="">
    <meta name="author" content="Monnehan Georges Alain">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cours et exercices</title>

    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <!-- Load Require CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font CSS -->
    <link href="{% static 'assets/css/boxicon.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- Load Tempalte CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/templatemo.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nav-styles.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
		
</head>

<body>
    <!-- Start navigation bar -->
    <nav class="container-fluid">
        <div id="logo" class="col-md-4 col-xs-8">G. A. MONNEHAN, Prof.</div>
        <ul class="col-md-8 menu">
            <li><a href="{% url 'index' %}"><i class="fas fa-home"></i>&nbsp; Accueil</a></li>
            <li><a href="{% url 'curriculum:index' %}"><i class="fas fa-award"></i>&nbsp; Compétences</a></li>
            <li><a href="{% url 'curriculum:skills' %}"><i class="fas fa-file-invoice"></i>&nbsp; CV</a></li>
            <li><a href="{% url 'teaching:courses' %}"><i class="fas fa-chalkboard-teacher"></i>&nbsp; Cours</a></li>
            <li><a href="{% url 'authentication:login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp; Connexion</a></li>
            <li><a href="{% url 'authentication:registration' %}"><i class="fas fa-user-circle"></i>&nbsp; Inscription</a></li>
        </ul>

        <!-- Media query -->
        <div class="dropdown col-sx-4">
            <button class="btn dropbtn"><i class="fas fa-bars"></i> Menu</button>
            <div class="dropdown-content">
                <a href="{% url 'index' %}"><i class="fas fa-home"></i>&nbsp; Accueil</a>
                <a href="{% url 'curriculum:index' %}"><i class="fas fa-award"></i>&nbsp; Compétences</a>
                <a href="{% url 'curriculum:skills' %}"><i class="fas fa-file-invoice"></i>&nbsp; CV</a>
                <a href="{% url 'teaching:courses' %}"><i class="fas fa-chalkboard-teacher"></i>&nbsp; Cours</a>
                <a href="{% url 'authentication:login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp; Connexion</a>
                <a href="{% url 'authentication:registration' %}"><i class="fas fa-user-circle"></i>&nbsp; Inscription</a>
            </div>
        </div>
    </nav>
    <!-- End navigation bar -->

    

    <!-- Start Our Work -->
    <section class="container py-5" style="margin-top: 100px;">
        <ul>
            {% for matiere in disciplines %}
                <li>{{ matiere.id }}</li>
                <li>{{ matiere.titre }}</li>
                <li>{{ matiere.description }}</li>
                <li>{{ matiere.module }}</li>
            {% endfor %}
        </ul>

        <div class="row projects gx-lg-5">
            {% for matiere in disciplines %}
            <a href="{% static 'images/physique_nucleaire_appliquee.pdf' %}" target="_blank" class="col-sm-6 col-lg-4 text-decoration-none project marketing social business">
                <div class="service-work overflow-hidden card mb-5 mx-5 m-sm-0">
                    <img class="card-img-top" src="{% static 'assets/img/chimie.jpg' %}" alt="...">
                    <div class="card-body">
                        <h5 class="card-title light-300 text-dark">{{ matiere.titre }}</h5>
                        <p class="card-text light-300 text-dark">{{ matiere.description }}</p>
                        <span class="text-decoration-none text-primary light-300">
                            Suivre le cours <i class='bx bxs-hand-right ms-1'></i>
                        </span>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </section>
    <!-- End Our Work -->

    <!-- Start Footer -->
    <footer style="border-top: 1px solid #FFF;">
        <div class="container">
            <div class="row">
                <div class="col-md-12 wow fadeIn" data-wow-delay="0.9s">
                    <p>Copyright &copy; 2021 - Monnehan Georges Alain . All rights reserved</p>
                    <ul class="social-icon">
                        <li style="color: brown;"><a href="#" class="fa fa-facebook"></a></li>
                        <li><a href="#" class="fa fa-twitter"></a></li>
                        <li><a href="#" class="fa fa-linkedin"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <!-- Bootstrap -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Lightbox -->
    <script src="{% static 'assets/js/fslightbox.js' %}"></script>
    <script>
        fsLightboxInstances['gallery'].props.loadOnlyCurrentSource = true;
    </script>
    <!-- Load jQuery require for isotope -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <!-- Isotope -->
    <script src="{% static 'assets/js/isotope.pkgd.js' %}"></script>
    <!-- Page Script -->
    <script>
        $(window).load(function() {
            // init Isotope
            var $projects = $('.projects').isotope({
                itemSelector: '.project',
                layoutMode: 'fitRows'
            });
            $(".filter-btn").click(function() {
                var data_filter = $(this).attr("data-filter");
                $projects.isotope({
                    filter: data_filter
                });
                $(".filter-btn").removeClass("active");
                $(".filter-btn").removeClass("shadow");
                $(this).addClass("active");
                $(this).addClass("shadow");
                return false;
            });
        });
    </script>
    <!-- Templatemo -->
    <script src="{% static 'assets/js/templatemo.js' %}"></script>
    <!-- Custom -->
    <script src="{% static 'assets/js/custom.js' %}"></script>

</body>
</html>